#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "auth.pb.h"

namespace Auth
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void Register(RegisterRequest *request, RegisterResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void Login(LoginRequest *request, LoginResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using RegisterDone = std::function<void (RegisterResponse *, srpc::RPCContext *)>;
using LoginDone = std::function<void (LoginResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_Register_task(RegisterDone done);
	srpc::SRPCClientTask *create_Login_task(LoginDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_Register_task(RegisterDone done);
	srpc::SRPCHttpClientTask *create_Login_task(LoginDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_Register_task(RegisterDone done);
	srpc::BRPCClientTask *create_Login_task(LoginDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_Register_task(RegisterDone done);
	srpc::TRPCClientTask *create_Login_task(LoginDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_Register_task(RegisterDone done);
	srpc::TRPCHttpClientTask *create_Login_task(LoginDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("Auth")
{
	this->srpc::RPCService::add_method("Register",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Register);
		});

	this->srpc::RPCService::add_method("Login",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Login);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> SRPCClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> SRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> BRPCClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> BRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("/Auth/Register", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> TRPCClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("/Auth/Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("/Auth/Login", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> TRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("/Auth/Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_Register_task(RegisterDone done)
{
	auto *task = this->create_rpc_client_task("/Auth/Register", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_Login_task(LoginDone done)
{
	auto *task = this->create_rpc_client_task("/Auth/Login", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("Auth")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("Auth")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Register_task(RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Login_task(LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace Auth

